trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: Terraform Module Variables
stages:
  - stage: __default
    jobs:
      - job: null
        displayName: Build, Test and Deploy
        timeoutInMinutes: 130
        steps:
          - task: GoTool@0
            inputs:
              version: 1.16
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 0.13.6
          - task: Bash@3
            displayName: Go get test dependencies
            inputs:
              targetType: inline
              script: "go mod download -x"
              workingDirectory: $(Build.SourcesDirectory)/test
          - task: DownloadSecureFile@1
            inputs:
              secureFile: 28602a18-0e2e-4a9b-94ab-220ba97b039c
          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Agent.TempDirectory)
              Contents: "*.tfvars"
              TargetFolder: $(Build.SourcesDirectory)/examples
          - task: Bash@3
            displayName: Go test
            inputs:
              targetType: inline
              script: "go test -timeout 2h -v"
              workingDirectory: $(Build.SourcesDirectory)/test
            env:
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              TF_VAR_AKS_CLIENT_ID_SECRET: $(TF_VAR_aks_client_id_secret)
              TF_VAR_AKS_AAD_SERVER_ID_SECRET: $(TF_VAR_aks_aad_server_id_secret)
          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/examples
              Contents: "*.tfvars"
            condition: always()
          - task: Npm@1
            displayName: Npm Install
            inputs:
              command: ci
          - task: Bash@3
            displayName: Release via semantic-release
            inputs:
              targetType: inline
              script: npx semantic-release
            env:
              GH_TOKEN: $(BOT_GH_TOKEN)
