variable "resource_group_name" {}
variable "cluster_prefix" {}
variable "environment_name" {}
variable "unique_id" {}
variable "aks_version" {}
variable "aks_client_id" {}
variable "aks_client_id_secret" {}
variable "aks_aad_client_id" {}
variable "aks_aad_server_id" {}
variable "aks_aad_server_id_secret" {}
variable "enable_log_analytics_workspace" {}
variable "tags" {}
